/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabalho1;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Depositar extends javax.swing.JFrame {

    /**
     * Creates new form Depositar
     */
    public Depositar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tbNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tbValor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número da conta");

        jLabel2.setText("Valor para depósito");

        jButton1.setText("Confirmar");

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbValor, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(tbNum)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tbNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tbValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double valor = Double.parseDouble(tbValor.getText());
        if(tbValor.getText().equals("")||tbNum.getText().equals(""))
            JOptionPane.showMessageDialog(null, "preencha todos os campos");
        else{
            
            if (Integer.parseInt(tbNum.getText()) != Principal.conta1.getNumero()
                && Integer.parseInt(tbNum.getText()) != Poupanca.conta2.getNumero()
                && Integer.parseInt(tbNum.getText()) != Especial.conta3.getNumero()){
                JOptionPane.showMessageDialog(null, ("conta inválida, try again!"));
            }
            else if(Integer.parseInt(tbNum.getText()) == Principal.conta1.getNumero()){
                Object[] botoes = { "Confirmar", "Cancelar" };

            int resposta = JOptionPane.showOptionDialog(null,
                            "Titular: "+Principal.conta1.getNome()+"\nConfirme o depósito",
                            "Confirmação",
                            JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                            botoes, botoes[0]);
            if(resposta == 0) {
                 Principal.conta1.setSaldo(Principal.conta1.getSaldo() + valor);
                 JOptionPane.showMessageDialog(this, "Depósito efetuado com sucesso");
                dispose();
            }
                else if(resposta==1){
                    JOptionPane.showMessageDialog(this, "Depósito cancelado com sucesso");
                dispose();    
                        }
            
            }
            else if(Integer.parseInt(tbNum.getText()) == Poupanca.conta2.getNumero()){
                Object[] botoes = { "Confirmar", "Cancelar" };

            int resposta = JOptionPane.showOptionDialog(null,
                            "Titular: "+Poupanca.conta2.getNome()+"\nConfirme o depósito",
                            "Confirmação",
                            JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                            botoes, botoes[0]);
            if(resposta == 0) {
                 Poupanca.conta2.setSaldo(Poupanca.conta2.getSaldo() + valor);
                 JOptionPane.showMessageDialog(this, "Depósito efetuado com sucesso");
                dispose();
            }
                else if(resposta==1){
                    JOptionPane.showMessageDialog(this, "Depósito cancelado com sucesso");
                dispose();    
                        }
            
            }
            
            else if(Integer.parseInt(tbNum.getText()) == Especial.conta3.getNumero()){
                Object[] botoes = { "Confirmar", "Cancelar" };

            int resposta = JOptionPane.showOptionDialog(null,
                            "Titular: "+Especial.conta3.getNome()+"\nConfirme o depósito",
                            "Confirmação",
                            JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                            botoes, botoes[0]);
            if(resposta == 0) {
                 Especial.conta3.setSaldo(Especial.conta3.getSaldo() + valor);
                 JOptionPane.showMessageDialog(this, "Depósito efetuado com sucesso");
                dispose();
            }
                else if(resposta==1){
                    JOptionPane.showMessageDialog(this, "Depósito cancelado com sucesso");
                dispose();    
                        }
            
            }
            
            new IGContas ().setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new IGContas ().setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Depositar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tbNum;
    private javax.swing.JTextField tbValor;
    // End of variables declaration//GEN-END:variables
}
