/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabalho1;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Sacar extends javax.swing.JFrame {

    /**
     * Creates new form Sacar
     */
    
    
    
    public Sacar(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tbNum = new javax.swing.JTextField();
        tbSaldo = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número da Conta");

        jLabel2.setText("  Valor para Sacar");

        jButton1.setText("Confirmar");

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(tbNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbSaldo, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tbSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(105, 105, 105))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void tbSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSaldoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int num = Integer.parseInt(tbNum.getText());
        double valor = Double.parseDouble(tbSaldo.getText());
        
        if(tbSaldo.getText().equals("")||tbNum.getText().equals(""))
            JOptionPane.showMessageDialog(null, "preencha todos os campos");
        else{
            if (Integer.parseInt(tbNum.getText()) != Principal.conta1.getNumero()
                && Integer.parseInt(tbNum.getText()) != Poupanca.conta2.getNumero()
                && Integer.parseInt(tbNum.getText()) != Especial.conta3.getNumero()){
                JOptionPane.showMessageDialog(null, ("conta inválida, try again!"));
            }
            else{
            
            if(Integer.parseInt(tbNum.getText()) == Principal.conta1.getNumero()) {
                Object[] botoes = { "Confirmar", "Cancelar" };

                int resposta = JOptionPane.showOptionDialog(null,
                                "Titular: "+Principal.conta1.getNome()+"\nConfirme o saque",
                                "Confirmação",
                                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                                botoes, botoes[0]);
                if(resposta == 0) {
                    if(Principal.conta1.getSaldo() >= valor) {
                        Principal.conta1.setSaldo(Principal.conta1.getSaldo() - valor);
                        JOptionPane.showMessageDialog(this, "Saque efetuado com sucesso");
                    } else {
                        JOptionPane.showMessageDialog(this, "Saldo insuficiente");
                    }
                    dispose();
                } else if(resposta == 1) {
                    JOptionPane.showMessageDialog(this, "Saque cancelado com sucesso");
                    dispose();
                }
            } 
            if(Integer.parseInt(tbNum.getText()) == Poupanca.conta2.getNumero()) {
                
                Object[] botoes = { "Confirmar", "Cancelar" };

                int resposta = JOptionPane.showOptionDialog(null,
                                "Titular: "+Poupanca.conta2.getNome()+"\nConfirme o saque",
                                "Confirmação",
                                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                                botoes, botoes[0]);
                if(resposta == 0) {
                    if(Poupanca.conta2.getSaldo() >= valor) {
                       Poupanca.conta2.setSaldo(Poupanca.conta2.getSaldo() - valor);
                        JOptionPane.showMessageDialog(this, "Saque efetuado com sucesso");
                    } else {
                        JOptionPane.showMessageDialog(this, "Saldo insuficiente");
                    }
                    dispose();
                    } else if(resposta == 1) {
                    JOptionPane.showMessageDialog(this, "Saque cancelado com sucesso");
                    dispose();
                }
    }//GEN-LAST:event_jButton1ActionPerformed
        if(Integer.parseInt(tbNum.getText()) == Especial.conta3.getNumero()) {
                
                Object[] botoes = { "Confirmar", "Cancelar" };

                int resposta = JOptionPane.showOptionDialog(null,
                                "Titular: "+Especial.conta3.getNome()+"\nConfirme o saque",
                                "Confirmação",
                                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                                botoes, botoes[0]);
                if(resposta == 0) {
                    if(Especial.conta3.getSaldo() >= valor) {
                        Especial.conta3.setSaldo(Especial.conta3.getSaldo() - valor);
                        JOptionPane.showMessageDialog(this, "Saque efetuado com sucesso");
                        dispose();
                    } else {
                        if((Especial.conta3.getSaldo()+Especial.conta3.getLimite())>=valor){
                            double multa;
                            multa= valor + ((valor-Especial.conta3.getSaldo())*Especial.conta3.getMulta());
                            JOptionPane.showMessageDialog(this, "Saque feito usando cheque especial");
                            dispose();
                        }
                        else{
                        JOptionPane.showMessageDialog(this, "Saldo insuficiente");
                        dispose();
                        }
                    }
                    dispose();
                    } else if(resposta == 1) {
                    JOptionPane.showMessageDialog(this, "Saque cancelado com sucesso");
                    dispose();
                }
    }
            }
        new IGContas ().setVisible(true);
            this.setVisible(false);    
        }
            }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new IGContas ().setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sacar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField tbNum;
    private javax.swing.JTextField tbSaldo;
    // End of variables declaration//GEN-END:variables
}
